project:
  type: website
  output-dir: docs

format:
  html:
    css: styles/styles.css    # put your CSS at styles/styles.css (or change the path)

website:
  title: "Caldwell Muboyi Portfolio"

  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html
      - text: Projects
        menu:
          - text: Customer Churn Analysis
            href: projects/churn-analysis.html
          - text: Power BI Dashboards
            href: projects/powerbi-dashboards.html
      - text: BCG Tech Store
        menu:
          - text: Store Home
            href: bcg-tech-store/index.html
          - text: Products
            href: bcg-tech-store/products.html
          - text: Contact
            href: bcg-tech-store/contact.html
      - text: BCG Tokwe Mukosi Fish
        menu:
          - text: Fish Home
            href: bcg-fish/index.html
          - text: Products
            href: bcg-fish/products.html
          - text: Contact
            href: bcg-fish/contact.html
      - text: Contact
        href: contact.html

