navbar:
  background: "#002855"
  left:
    - text: Home
      href: index.qmd
    - text: About
      href: about.qmd
    - text: Projects
      menu:
        - text: Customer Churn Analysis
          href: projects/churn-analysis.qmd
        - text: Power BI Dashboards
          href: projects/powerbi-dashboards.qmd
    - text: BCG Tech Store
      menu:
        - text: Store Home
          href: bcg-tech-store/index.qmd
        - text: Products
          href: bcg-tech-store/products.qmd
        - text: Contact
          href: bcg-tech-store/contact.qmd
    - text: BCG Tokwe Mukosi Fish
      menu:
        - text: Fish Home
          href: bcg-fish/index.qmd
        - text: Products
          href: bcg-fish/products.qmd
        - text: Contact
          href: bcg-fish/contact.qmd
    - text: Contact
      href: contact.qmd

